/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKeyTokensListResponse {
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Vec<crate::models::ApiKeyToken>>,
}

impl ApiKeyTokensListResponse {
    pub fn new() -> ApiKeyTokensListResponse {
        ApiKeyTokensListResponse {
            tokens: None,
        }
    }
}


