/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKeyToken {
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ip_allowlist_mode", skip_serializing_if = "Option::is_none")]
    pub ip_allowlist_mode: Option<IpAllowlistModeType>,
    #[serde(rename = "ip_allowlist", skip_serializing_if = "Option::is_none")]
    pub ip_allowlist: Option<Vec<String>>,
}

impl ApiKeyToken {
    pub fn new() -> ApiKeyToken {
        ApiKeyToken {
            token_id: None,
            updated_at: None,
            created_at: None,
            name: None,
            ip_allowlist_mode: None,
            ip_allowlist: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IpAllowlistModeType {
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "explicit")]
    Explicit,
}

impl Default for IpAllowlistModeType {
    fn default() -> IpAllowlistModeType {
        Self::Disabled
    }
}

