/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogActor : The user or service that performed the action. Absent if the actor is unknown.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogActor {
    /// Email address of the actor. Absent if unavailable.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// UUID of the actor.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Additional actor-specific data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// Display name of the actor. Absent if unavailable.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Actor type (e.g. member, api_key, system).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl AuditLogActor {
    /// The user or service that performed the action. Absent if the actor is unknown.
    pub fn new() -> AuditLogActor {
        AuditLogActor {
            email: None,
            id: None,
            metadata: None,
            name: None,
            _type: None,
        }
    }
}


