/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.2
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogContext : Request context at the time of the event. Absent if context was not captured.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogContext {
    /// Country code derived from the request IP.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// IP address the request originated from.
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// Additional context-specific data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// User agent of the client that made the request.
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
}

impl AuditLogContext {
    /// Request context at the time of the event. Absent if context was not captured.
    pub fn new() -> AuditLogContext {
        AuditLogContext {
            country: None,
            ip: None,
            metadata: None,
            user_agent: None,
        }
    }
}


