/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogTarget : A resource the action was performed on.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogTarget {
    /// UUID of the resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Additional resource-specific data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// Display name of the resource. Absent if unavailable.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Resource type (e.g. notification, segment, journey, app).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl AuditLogTarget {
    /// A resource the action was performed on.
    pub fn new() -> AuditLogTarget {
        AuditLogTarget {
            id: None,
            metadata: None,
            name: None,
            _type: None,
        }
    }
}


