/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BeginLiveActivityRequest {
    #[serde(rename = "push_token")]
    pub push_token: String,
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
}

impl BeginLiveActivityRequest {
    pub fn new(push_token: String, subscription_id: String) -> BeginLiveActivityRequest {
        BeginLiveActivityRequest {
            push_token,
            subscription_id,
        }
    }
}


