/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CopyTemplateRequest {
    /// Destination OneSignal App ID in UUID v4 format.
    #[serde(rename = "target_app_id")]
    pub target_app_id: String,
}

impl CopyTemplateRequest {
    pub fn new(target_app_id: String) -> CopyTemplateRequest {
        CopyTemplateRequest {
            target_app_id,
        }
    }
}


