/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateApiKeyResponse {
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
    #[serde(rename = "formatted_token", skip_serializing_if = "Option::is_none")]
    pub formatted_token: Option<String>,
}

impl CreateApiKeyResponse {
    pub fn new() -> CreateApiKeyResponse {
        CreateApiKeyResponse {
            token_id: None,
            formatted_token: None,
        }
    }
}


