/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateSubscriptionRequestBody {
    #[serde(rename = "subscription", skip_serializing_if = "Option::is_none")]
    pub subscription: Option<Box<crate::models::SubscriptionObject>>,
    #[serde(rename = "retain_previous_owner", skip_serializing_if = "Option::is_none")]
    pub retain_previous_owner: Option<bool>,
}

impl CreateSubscriptionRequestBody {
    pub fn new() -> CreateSubscriptionRequestBody {
        CreateSubscriptionRequestBody {
            subscription: None,
            retain_previous_owner: None,
        }
    }
}


