/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomEventsRequest {
    #[serde(rename = "events")]
    pub events: Vec<crate::models::CustomEvent>,
}

impl CustomEventsRequest {
    pub fn new(events: Vec<crate::models::CustomEvent>) -> CustomEventsRequest {
        CustomEventsRequest {
            events,
        }
    }
}


