/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeletePlayerBadRequestResponse {
    #[serde(rename = "erorrs", skip_serializing_if = "Option::is_none")]
    pub erorrs: Option<Vec<String>>,
}

impl DeletePlayerBadRequestResponse {
    pub fn new() -> DeletePlayerBadRequestResponse {
        DeletePlayerBadRequestResponse {
            erorrs: None,
        }
    }
}


