/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// DuplicateJourneyRequest : Optional body for Duplicate journey. Only overrides is applied. A journey field sent at the top level is ignored.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DuplicateJourneyRequest {
    #[serde(rename = "overrides", skip_serializing_if = "Option::is_none")]
    pub overrides: Option<Box<crate::models::DuplicateJourneyOverrides>>,
}

impl DuplicateJourneyRequest {
    /// Optional body for Duplicate journey. Only overrides is applied. A journey field sent at the top level is ignored.
    pub fn new() -> DuplicateJourneyRequest {
        DuplicateJourneyRequest {
            overrides: None,
        }
    }
}


