/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// EmailReputationResponse : App-wide email bounce and spam complaint rates, broken out by time window.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmailReputationResponse {
    /// Bounce and complaint rates for email delivered over the last 24 hours.
    #[serde(rename = "last_24_hours", skip_serializing_if = "Option::is_none")]
    pub last_24_hours: Option<Box<crate::models::EmailReputationWindow>>,
    /// Bounce and complaint rates for email delivered over the last 7 days.
    #[serde(rename = "last_7_days", skip_serializing_if = "Option::is_none")]
    pub last_7_days: Option<Box<crate::models::EmailReputationWindow>>,
    /// Bounce and complaint rates for email delivered over the last 30 days.
    #[serde(rename = "last_30_days", skip_serializing_if = "Option::is_none")]
    pub last_30_days: Option<Box<crate::models::EmailReputationWindow>>,
}

impl EmailReputationResponse {
    /// App-wide email bounce and spam complaint rates, broken out by time window.
    pub fn new() -> EmailReputationResponse {
        EmailReputationResponse {
            last_24_hours: None,
            last_7_days: None,
            last_30_days: None,
        }
    }
}


