/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// EmailWarmUpStage : Channel: Email One stage of an Auto Warm Up campaign's sending schedule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmailWarmUpStage {
    /// ISO 8601 timestamp for the start of this stage. Sending for this stage will not begin before this time.
    #[serde(rename = "start")]
    pub start: String,
    /// ISO 8601 timestamp for the end of this stage. This stage's quota is expected to be sent by this time.
    #[serde(rename = "end")]
    pub end: String,
    /// Number of emails to send during this stage.
    #[serde(rename = "quota")]
    pub quota: i32,
    /// Whether this stage has been picked up and acknowledged by the warm-up scheduler. Not accepted on create. This is only present when reading back a campaign.
    #[serde(rename = "acked", skip_serializing_if = "Option::is_none")]
    pub acked: Option<bool>,
}

impl EmailWarmUpStage {
    /// Channel: Email One stage of an Auto Warm Up campaign's sending schedule.
    pub fn new(start: String, end: String, quota: i32) -> EmailWarmUpStage {
        EmailWarmUpStage {
            start,
            end,
            quota,
            acked: None,
        }
    }
}


