/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// EmailReputationWindow : Email reputation rates for a single time window. Each rate is a fraction of successfully delivered emails (for example, `0.02` means 2%). Both rates are `0` when no email was successfully delivered in the window.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmailReputationWindow {
    /// The fraction of successfully delivered emails that hard or soft bounced during the window.
    #[serde(rename = "bounce_rate", skip_serializing_if = "Option::is_none")]
    pub bounce_rate: Option<f64>,
    /// The fraction of successfully delivered emails that recipients reported as spam during the window.
    #[serde(rename = "complaint_rate", skip_serializing_if = "Option::is_none")]
    pub complaint_rate: Option<f64>,
}

impl EmailReputationWindow {
    /// Email reputation rates for a single time window. Each rate is a fraction of successfully delivered emails (for example, `0.02` means 2%). Both rates are `0` when no email was successfully delivered in the window.
    pub fn new() -> EmailReputationWindow {
        EmailReputationWindow {
            bounce_rate: None,
            complaint_rate: None,
        }
    }
}


