/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EstimateNotificationRecipientsSuccessResponse {
    /// The estimated audience size based on the user targeting method you've set on the message, and the specific platforms the message is targeted to send to.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The estimated audience size before the plan's web push subscriber cap is applied. Present only when `cap_applied` is `true`; `null` otherwise.
    #[serde(rename = "uncapped_count", skip_serializing_if = "Option::is_none")]
    pub uncapped_count: Option<i32>,
    /// Whether `count` was reduced because the app is on a plan that caps the number of web push subscribers it can send to.
    #[serde(rename = "cap_applied", skip_serializing_if = "Option::is_none")]
    pub cap_applied: Option<bool>,
    /// The mobile equivalent of `cap_applied`. Whether mobile push deliveries will be dropped for this send because the org is over its plan's mobile push subscriber cap. `false` when the notification doesn't target any mobile push platforms.
    #[serde(rename = "mobile_suppressed", skip_serializing_if = "Option::is_none")]
    pub mobile_suppressed: Option<bool>,
    /// How many mobile push recipients the `count` excludes due to the plan's mobile push subscriber cap. `0` when `mobile_suppressed` is `false`.
    #[serde(rename = "mobile_excluded_count", skip_serializing_if = "Option::is_none")]
    pub mobile_excluded_count: Option<i32>,
}

impl EstimateNotificationRecipientsSuccessResponse {
    pub fn new() -> EstimateNotificationRecipientsSuccessResponse {
        EstimateNotificationRecipientsSuccessResponse {
            count: None,
            uncapped_count: None,
            cap_applied: None,
            mobile_suppressed: None,
            mobile_excluded_count: None,
        }
    }
}


