/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExportEventsSuccessResponse {
    #[serde(rename = "csv_file_url", skip_serializing_if = "Option::is_none")]
    pub csv_file_url: Option<String>,
}

impl ExportEventsSuccessResponse {
    pub fn new() -> ExportEventsSuccessResponse {
        ExportEventsSuccessResponse {
            csv_file_url: None,
        }
    }
}


