/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.0.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenericError {
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<serde_json::Value>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<serde_json::Value>,
}

impl GenericError {
    pub fn new() -> GenericError {
        GenericError {
            errors: None,
            success: None,
            reference: None,
        }
    }
}


