/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSegmentSuccessResponse {
    /// The number of subscribers matching this segment.
    #[serde(rename = "subscriber_count", skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<crate::models::SegmentDetails>>,
}

impl GetSegmentSuccessResponse {
    pub fn new() -> GetSegmentSuccessResponse {
        GetSegmentSuccessResponse {
            subscriber_count: None,
            payload: None,
        }
    }
}


