/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.0.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSegmentsSuccessResponse {
    /// The number of Segments in the response.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    /// Set with the offset query parameter. Default 0.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of Segments returned. Default 300.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// An array containing the Segment information.
    #[serde(rename = "segments", skip_serializing_if = "Option::is_none")]
    pub segments: Option<Vec<crate::models::SegmentData>>,
}

impl GetSegmentsSuccessResponse {
    pub fn new() -> GetSegmentsSuccessResponse {
        GetSegmentsSuccessResponse {
            total_count: None,
            offset: None,
            limit: None,
            segments: None,
        }
    }
}


