/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentifyUserConflictResponse {
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::IdentifyUserConflictResponseErrorsInner>>,
}

impl IdentifyUserConflictResponse {
    pub fn new() -> IdentifyUserConflictResponse {
        IdentifyUserConflictResponse {
            errors: None,
        }
    }
}


