/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyMessageStats : Delivery stats for a message-sending node. Present only on send_push, send_email, send_sms, send_iam, and send_webhook nodes. The keys inside totals depend on the node's channel.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyMessageStats {
    /// All-time totals for this node, keyed by channel-specific stat name.
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<::std::collections::HashMap<String, f32>>,
}

impl JourneyMessageStats {
    /// Delivery stats for a message-sending node. Present only on send_push, send_email, send_sms, send_iam, and send_webhook nodes. The keys inside totals depend on the node's channel.
    pub fn new() -> JourneyMessageStats {
        JourneyMessageStats {
            totals: None,
        }
    }
}


