/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyReentryRules : Controls whether and how soon a user can re-enter the journey. null means re-entry is not allowed.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyReentryRules {
    /// Minimum seconds before a user can re-enter. Must be at least 600 (10 minutes).
    #[serde(rename = "duration_seconds", skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i32>,
}

impl JourneyReentryRules {
    /// Controls whether and how soon a user can re-enter the journey. null means re-entry is not allowed.
    pub fn new() -> JourneyReentryRules {
        JourneyReentryRules {
            duration_seconds: None,
        }
    }
}


