/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyListResponse {
    /// Journeys ordered by creation time, newest first.
    #[serde(rename = "journeys", skip_serializing_if = "Option::is_none")]
    pub journeys: Option<Vec<crate::models::JourneyListItem>>,
    /// true if more journeys exist beyond this page.
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Cursor for the next page. Present only when has_more is true.
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl JourneyListResponse {
    pub fn new() -> JourneyListResponse {
        JourneyListResponse {
            journeys: None,
            has_more: None,
            next_cursor: None,
        }
    }
}


