/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyListAudience : Entry audience reduced to its kind. Use View journey for the full audience configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyListAudience {
    /// Audience kind.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<KindType>,
}

impl JourneyListAudience {
    /// Entry audience reduced to its kind. Use View journey for the full audience configuration.
    pub fn new() -> JourneyListAudience {
        JourneyListAudience {
            kind: None,
        }
    }
}

/// Audience kind.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KindType {
    #[serde(rename = "segment")]
    Segment,
    #[serde(rename = "event_trigger")]
    EventTrigger,
}

impl Default for KindType {
    fn default() -> KindType {
        Self::Segment
    }
}

