/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyTimeWindow : A wall-clock window. Each window must span at least 15 minutes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyTimeWindow {
    /// When the window opens.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<Box<crate::models::JourneyTimePoint>>,
    /// When the window closes.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<Box<crate::models::JourneyTimePoint>>,
    /// Day of week, 1 = Monday. Omit to apply the window to every day.
    #[serde(rename = "day_of_week", skip_serializing_if = "Option::is_none")]
    pub day_of_week: Option<i32>,
}

impl JourneyTimeWindow {
    /// A wall-clock window. Each window must span at least 15 minutes.
    pub fn new() -> JourneyTimeWindow {
        JourneyTimeWindow {
            start: None,
            end: None,
            day_of_week: None,
        }
    }
}


