/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyTimePoint {
    /// Hour of day, 0-23.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<i32>,
    /// Minute of hour, 0-59. Defaults to 0.
    #[serde(rename = "minute", skip_serializing_if = "Option::is_none")]
    pub minute: Option<i32>,
}

impl JourneyTimePoint {
    pub fn new() -> JourneyTimePoint {
        JourneyTimePoint {
            hour: None,
            minute: None,
        }
    }
}


