/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyBranchStats : Stats for a single branch of a branching node. Keyed in the response by the branch's server-assigned id.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyBranchStats {
    /// Users who took this branch.
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<i32>,
}

impl JourneyBranchStats {
    /// Stats for a single branch of a branching node. Keyed in the response by the branch's server-assigned id.
    pub fn new() -> JourneyBranchStats {
        JourneyBranchStats {
            completed: None,
        }
    }
}


