/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyEarlyExit : Conditions that remove a user from the journey before it completes. At least one rule must be set under rules. Send null to remove early exit entirely.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyEarlyExit {
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Box<crate::models::JourneyEarlyExitRules>>,
    /// Tag key-value pairs applied when a user exits early.
    #[serde(rename = "tag_on_early_exit", skip_serializing_if = "Option::is_none")]
    pub tag_on_early_exit: Option<::std::collections::HashMap<String, String>>,
}

impl JourneyEarlyExit {
    /// Conditions that remove a user from the journey before it completes. At least one rule must be set under rules. Send null to remove early exit entirely.
    pub fn new() -> JourneyEarlyExit {
        JourneyEarlyExit {
            rules: None,
            tag_on_early_exit: None,
        }
    }
}


