/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyEarlyExitRulesOnSegment {
    /// Exit when the user enters any of these segments.
    #[serde(rename = "included_segment_ids", skip_serializing_if = "Option::is_none")]
    pub included_segment_ids: Option<Vec<String>>,
}

impl JourneyEarlyExitRulesOnSegment {
    pub fn new() -> JourneyEarlyExitRulesOnSegment {
        JourneyEarlyExitRulesOnSegment {
            included_segment_ids: None,
        }
    }
}


