/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneyWaitUntilExpiration : Optional expiration timer. null waits indefinitely.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyWaitUntilExpiration {
    /// Seconds to wait before the timer fires. Minimum 60, maximum 31556952 (1 year).
    #[serde(rename = "duration_seconds", skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i32>,
    /// When true, the user exits the journey when the timer fires; when false, the user continues to convergence.
    #[serde(rename = "exits", skip_serializing_if = "Option::is_none")]
    pub exits: Option<bool>,
}

impl JourneyWaitUntilExpiration {
    /// Optional expiration timer. null waits indefinitely.
    pub fn new() -> JourneyWaitUntilExpiration {
        JourneyWaitUntilExpiration {
            duration_seconds: None,
            exits: None,
        }
    }
}


