/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// Journey : Full journey representation returned by the detail, create, and update endpoints.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Journey {
    /// Journey UUID. Read-only.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// UUID of the app the journey belongs to. Read-only.
    #[serde(rename = "app_id", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    /// Journey name, up to 300 characters.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Journey description, up to 1024 characters. Defaults to an empty string.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<StateType>,
    /// ISO 8601 creation time. Read-only.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// ISO 8601 last-update time. Read-only.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// ISO 8601 time the journey was activated, or null. Read-only. May stay null briefly after you set state to active: activation is enqueued, and started_at populates once the journey finishes processing.
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// ISO 8601 time the journey was archived, or null. Read-only.
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<String>,
    /// Origin of the journey, for example public_api or dashboard. Read-only.
    #[serde(rename = "created_source", skip_serializing_if = "Option::is_none")]
    pub created_source: Option<String>,
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<Box<crate::models::JourneyAudience>>,
    #[serde(rename = "early_exit", skip_serializing_if = "Option::is_none")]
    pub early_exit: Option<Box<crate::models::JourneyEarlyExit>>,
    #[serde(rename = "reentry_rules", skip_serializing_if = "Option::is_none")]
    pub reentry_rules: Option<Box<crate::models::JourneyReentryRules>>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<crate::models::JourneySchedule>>,
    /// Ordered list of journey nodes.
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Vec<crate::models::JourneyNode>>,
    /// Opaque optimistic-concurrency token. Read-only. Pass it back on update to guard against overwriting a concurrent change (409). Send it back exactly as read; do not construct or parse it.
    #[serde(rename = "concurrency_key", skip_serializing_if = "Option::is_none")]
    pub concurrency_key: Option<String>,
}

impl Journey {
    /// Full journey representation returned by the detail, create, and update endpoints.
    pub fn new() -> Journey {
        Journey {
            id: None,
            app_id: None,
            name: None,
            description: None,
            state: None,
            created_at: None,
            updated_at: None,
            started_at: None,
            archived_at: None,
            created_source: None,
            audience: None,
            early_exit: None,
            reentry_rules: None,
            schedule: None,
            nodes: None,
            concurrency_key: None,
        }
    }
}

/// Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StateType {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for StateType {
    fn default() -> StateType {
        Self::Draft
    }
}

