/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// JourneySchedule : Optional future start and/or stop time. null means no scheduled activation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneySchedule {
    /// ISO 8601 start time. Use UTC (Z or +00:00). Must be at least 5 minutes in the future.
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<String>,
    /// ISO 8601 stop time. Use UTC (Z or +00:00). Must be in the future and later than start_at.
    #[serde(rename = "stop_at", skip_serializing_if = "Option::is_none")]
    pub stop_at: Option<String>,
    /// Read-only. Present when a scheduling error occurred.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl JourneySchedule {
    /// Optional future start and/or stop time. null means no scheduled activation.
    pub fn new() -> JourneySchedule {
        JourneySchedule {
            start_at: None,
            stop_at: None,
            error: None,
        }
    }
}


