/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyEarlyExitRulesOnEvent {
    /// Exit when this event occurs. Up to 255 characters.
    #[serde(rename = "name")]
    pub name: String,
}

impl JourneyEarlyExitRulesOnEvent {
    pub fn new(name: String) -> JourneyEarlyExitRulesOnEvent {
        JourneyEarlyExitRulesOnEvent {
            name,
        }
    }
}


