/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAuditLogsSuccessResponse {
    /// Array of audit log events, ordered by occurred_at ascending.
    #[serde(rename = "audit_logs", skip_serializing_if = "Option::is_none")]
    pub audit_logs: Option<Vec<crate::models::AuditLogEvent>>,
    /// True if additional events exist beyond this page. Use next_cursor to fetch the next page.
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Opaque cursor to pass as cursor in the next request. Only present when has_more is true.
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl ListAuditLogsSuccessResponse {
    pub fn new() -> ListAuditLogsSuccessResponse {
        ListAuditLogsSuccessResponse {
            audit_logs: None,
            has_more: None,
            next_cursor: None,
        }
    }
}


