/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// PlatformDeliveryData : Hash of delivery statistics broken out by target device platform.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlatformDeliveryData {
    #[serde(rename = "edge_web_push", skip_serializing_if = "Option::is_none")]
    pub edge_web_push: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "chrome_web_push", skip_serializing_if = "Option::is_none")]
    pub chrome_web_push: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "firefox_web_push", skip_serializing_if = "Option::is_none")]
    pub firefox_web_push: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "safari_web_push", skip_serializing_if = "Option::is_none")]
    pub safari_web_push: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "android", skip_serializing_if = "Option::is_none")]
    pub android: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "ios", skip_serializing_if = "Option::is_none")]
    pub ios: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "sms", skip_serializing_if = "Option::is_none")]
    pub sms: Option<Box<crate::models::DeliveryData>>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<Box<crate::models::DeliveryData>>,
}

impl PlatformDeliveryData {
    /// Hash of delivery statistics broken out by target device platform.
    pub fn new() -> PlatformDeliveryData {
        PlatformDeliveryData {
            edge_web_push: None,
            chrome_web_push: None,
            firefox_web_push: None,
            safari_web_push: None,
            android: None,
            ios: None,
            sms: None,
            email: None,
        }
    }
}


