/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Purchase {
    /// The unique identifier of the purchased item.
    #[serde(rename = "sku")]
    pub sku: String,
    /// The amount, in USD, spent purchasing the item.
    #[serde(rename = "amount")]
    pub amount: String,
    /// The 3-letter ISO 4217 currency code. Required for correct storage and conversion of amount.
    #[serde(rename = "iso")]
    pub iso: String,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<f32>,
}

impl Purchase {
    pub fn new(sku: String, amount: String, iso: String) -> Purchase {
        Purchase {
            sku,
            amount,
            iso,
            count: None,
        }
    }
}


