/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */

/// SegmentDetails : Segment details. Only included when the include-segment-detail query parameter is set to true.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SegmentDetails {
    /// The unique identifier for the segment (UUID v4).
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The segment name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human-readable description for the segment. `null` when unset. Maximum 255 characters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Unix timestamp when the segment was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
    /// The source of the segment.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<SourceType>,
    /// Array of filter and operator objects defining the segment criteria. Uses the same format as the Create Segment API, so filters can be directly used to recreate or update the segment.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<crate::models::FilterExpression>>,
}

impl SegmentDetails {
    /// Segment details. Only included when the include-segment-detail query parameter is set to true.
    pub fn new() -> SegmentDetails {
        SegmentDetails {
            id: None,
            name: None,
            description: None,
            created_at: None,
            source: None,
            filters: None,
        }
    }
}

/// The source of the segment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "quickstart")]
    Quickstart,
}

impl Default for SourceType {
    fn default() -> SourceType {
        Self::Default
    }
}

