/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateUserRequest {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::PropertiesObject>>,
    #[serde(rename = "refresh_device_metadata", skip_serializing_if = "Option::is_none")]
    pub refresh_device_metadata: Option<bool>,
    #[serde(rename = "deltas", skip_serializing_if = "Option::is_none")]
    pub deltas: Option<Box<crate::models::PropertiesDeltas>>,
}

impl UpdateUserRequest {
    pub fn new() -> UpdateUserRequest {
        UpdateUserRequest {
            properties: None,
            refresh_device_metadata: None,
            deltas: None,
        }
    }
}


