/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.2.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateLiveActivityRequest {
    /// An internal name to assist with your campaign organization. This does not get displayed in the message itself.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "event")]
    pub event: EventType,
    /// This must match the ContentState interface you have defined within your Live Activity in your app.
    #[serde(rename = "event_updates")]
    pub event_updates: serde_json::Value,
    #[serde(rename = "contents", skip_serializing_if = "Option::is_none")]
    pub contents: Option<Box<crate::models::LanguageStringMap>>,
    #[serde(rename = "headings", skip_serializing_if = "Option::is_none")]
    pub headings: Option<Box<crate::models::LanguageStringMap>>,
    /// Sound file that is included in your app to play instead of the default device notification sound. Omit to disable vibration and sound for the notification.
    #[serde(rename = "sound", skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    /// Accepts Unix timestamp in seconds. When time reaches the configured stale date, the system considers the Live Activity out of date, and the ActivityState of the Live Activity changes to ActivityState.stale.
    #[serde(rename = "stale_date", skip_serializing_if = "Option::is_none")]
    pub stale_date: Option<i32>,
    /// Accepts Unix timestamp in seconds; only allowed if event is \"end\"
    #[serde(rename = "dismissal_date", skip_serializing_if = "Option::is_none")]
    pub dismissal_date: Option<i32>,
    /// Delivery priority through the the push provider (APNs). Pass 10 for higher priority notifications, or 5 for lower priority notifications. Lower priority notifications are sent based on the power considerations of the end user's device. If not set, defaults to 10. Some providers (APNs) allow for a limited budget of high priority notifications per hour, and if that budget is exceeded, the provider may throttle notification delivery.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl UpdateLiveActivityRequest {
    pub fn new(name: String, event: EventType, event_updates: serde_json::Value) -> UpdateLiveActivityRequest {
        UpdateLiveActivityRequest {
            name,
            event,
            event_updates,
            contents: None,
            headings: None,
            sound: None,
            stale_date: None,
            dismissal_date: None,
            priority: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "end")]
    End,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::Update
    }
}

