/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.2
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateSegmentSuccessResponse {
    /// true if the segment was updated successfully, false otherwise.
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// UUID of the updated segment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl UpdateSegmentSuccessResponse {
    pub fn new() -> UpdateSegmentSuccessResponse {
        UpdateSegmentSuccessResponse {
            success: None,
            id: None,
        }
    }
}


