/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::PropertiesObject>>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<crate::models::SubscriptionObject>>,
    #[serde(rename = "subscription_options", skip_serializing_if = "Option::is_none")]
    pub subscription_options: Option<Box<crate::models::UserSubscriptionOptions>>,
}

impl User {
    pub fn new() -> User {
        User {
            properties: None,
            identity: None,
            subscriptions: None,
            subscription_options: None,
        }
    }
}


