/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserIdentityBody {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<::std::collections::HashMap<String, String>>,
}

impl UserIdentityBody {
    pub fn new() -> UserIdentityBody {
        UserIdentityBody {
            identity: None,
        }
    }
}


